### ISSUE TITLE
Adding notifications (ie bump to 3.2)

### ISSUE THREAD

**Issue by dwyeraidan** [ayufan/pve-backup-server-dockerfiles#54] opened 2024-08-28 10:19 UTC
hey there,

Thanks for this project!

Version 3.2 has added notification functionality - would love to see this docker image updated with the newer version?

Thanks very much,

Aidan

**Comment by momuskk** [comment] 2024-10-17 11:09
In 3.2 there is also new option like "change-detection-mode".

**Comment by ayufan** [comment] 2024-12-13 07:25
Duplicate of https://github.com/ayufan/pve-backup-server-dockerfiles/issues/54

**Closed by ayufan** 2024-12-13 07:25 UTC
