### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by tgooro** [ayufan/pve-backup-server-dockerfiles#17] opened 2022-02-18 13:04 UTC
I installed this in Containner station on my Qnap NAS. I can access it using web interface but I am not able to login. I tried using admin for user and pbspbs for password but its not working.

Am i doing anything wrong or doing it in a wrong way?

**Comment by ayufan** [comment] 2022-02-18 14:06
Select PBS authentication service.

**Comment by captainfreya** [comment] 2022-02-19 21:00
Hi ayufan,

unfortunately I have the same login issue:

![Screenshot 2022-02-19 215529](https://user-images.githubusercontent.com/100047745/154818759-fdfb375c-4438-4487-9083-09d830f48d66.png)

I used "admin" as username and "pbspbs" as password and tried both "Proxmox Backup authentication server" and "Linux PAM standard authentication"... What am i doing wrong?

I'm using this version on Synology Diskstation:

![Screenshot 2022-02-19 215902](https://user-images.githubusercontent.com/100047745/154818903-dbfbd903-3dac-4325-b6e0-a3cc07683b06.png)

Thanks for your help.

**Comment by fila612** [comment] 2022-02-20 06:33
@captainfreya seems the same bahavoir like my issue #16 .
Important is also to setup the container with tmpfs volumes. you can check the auth.log file if you have the same entry like me.
(Da schein ein alter Kernel der Synology das Problem zu sein.)

**Comment by ayufan** [comment] 2022-02-24 16:11
Duplicate of https://github.com/ayufan/pve-backup-server-dockerfiles/issues/16

**Closed by ayufan** 2022-02-24 16:11 UTC
